# Generated by Django 4.2.3 on 2023-07-17 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jeonse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jeonse_deposit_amount",
                    models.BigIntegerField(default=0, verbose_name="전세금"),
                ),
                (
                    "wolse_deposit_amount",
                    models.BigIntegerField(default=0, verbose_name="월세금"),
                ),
                (
                    "wolse_monthly_amount",
                    models.IntegerField(default=0, verbose_name="월세"),
                ),
                (
                    "gwanlibi_monthly_amount",
                    models.IntegerField(default=0, verbose_name="월관리비"),
                ),
                ("loan_amount", models.BigIntegerField(default=0, verbose_name="대출금")),
                (
                    "loan_interest_rate",
                    models.FloatField(default=0.0, verbose_name="대출금리"),
                ),
                (
                    "total_monthly_payment",
                    models.IntegerField(default=0, verbose_name="월납부금"),
                ),
                ("total_area", models.FloatField(default=0.0, verbose_name="전용면적")),
                ("number_of_rooms", models.IntegerField(default=0, verbose_name="방개수")),
                (
                    "number_of_bathrooms",
                    models.IntegerField(default=0, verbose_name="욕실개수"),
                ),
                ("comment", models.TextField(default="", verbose_name="코멘트")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
