# Generated by Django 4.2.4 on 2023-08-10 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jeonse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jeonse_deposit_amount",
                    models.BigIntegerField(default=0, verbose_name="전세금"),
                ),
                (
                    "wolse_deposit_amount",
                    models.BigIntegerField(default=0, verbose_name="월세금"),
                ),
                (
                    "wolse_monthly_payment",
                    models.IntegerField(default=0, verbose_name="월세"),
                ),
                (
                    "gwanlibi_monthly_payment",
                    models.IntegerField(default=0, verbose_name="월관리비"),
                ),
                (
                    "total_monthly_payment",
                    models.IntegerField(default=0, verbose_name="총 월세"),
                ),
                (
                    "annual_interest_rate",
                    models.FloatField(default=0.0, verbose_name="대출 이자율"),
                ),
                ("total_area", models.FloatField(default=0.0, verbose_name="전용면적")),
                ("number_of_rooms", models.IntegerField(default=0, verbose_name="방개수")),
                (
                    "number_of_bathrooms",
                    models.IntegerField(default=0, verbose_name="욕실개수"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="코멘트"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
